language: generic
sudo: false

before_install:
  - bash -c 'echo `pwd`'
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./install-scimax-mac.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then evm install $EVM_EMACS --use --skip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cask; fi

matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis
    - env: OSX=true

  include:
    - os: linux
      sudo: false
      env: EVM_EMACS=emacs-25.1-travis
    - os: linux
      sudo: false
      env: EVM_EMACS=emacs-git-snapshot-travis
    - os: osx
      sudo: false
      env: OSX=true

install:
  - pwd
  - ls -al
  - ./.travis-install.sh
    
script:
  - emacs --version -l init.el
  - EMACS=`evm bin` make build
  - EMACS=`evm bin` make test
