install:
  - git submodule add https://github.com/jkitchin/emacs-win
  - cd emacs-win
  - git checkout 34a7ec32f8aaa0828fd3db04f258b7555115e281
  - git status
  - cd ..
  - git submodule add -f https://github.com/jkitchin/scimax-win-elpa elpa
  - git submodule init
  - git submodule update
  - C:\projects\scimax\emacs-win\bin\emacs.exe -batch -l debug-windows.el
  - C:\projects\scimax\emacs-win\bin\emacs.exe -batch -l init.el

build: off
